# Generated by Django 3.0.4 on 2020-07-17 13:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Classroom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_name', models.CharField(max_length=50)),
                ('subject', models.CharField(default='Add The Subject You Will be Teaching', max_length=50)),
                ('students', models.ManyToManyField(to='account_app.StudentProfile')),
                ('teacher', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='account_app.TeacherProfile')),
            ],
        ),
    ]
