# Generated by Django 3.0.4 on 2020-07-31 17:05

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0002_classroom_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='classroom',
            name='date_posted',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
