# Generated by Django 3.0.4 on 2020-03-22 19:59

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account_app', '0003_credit'),
        ('pokemon_app', '0002_auto_20200322_1855'),
    ]

    operations = [
        migrations.CreateModel(
            name='CardBuy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pokemon_app.CardSale')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account_app.Profile')),
            ],
        ),
    ]
