# Generated by Django 3.1.5 on 2021-02-05 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contributorprofile',
            name='image',
            field=models.ImageField(default='default.png', upload_to='profile_pics'),
        ),
        migrations.AlterField(
            model_name='contributorprofile',
            name='uploaded_images',
            field=models.ImageField(upload_to='my_images'),
        ),
    ]
