# Generated by Django 3.1.5 on 2021-02-05 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20210205_1525'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contributorprofile',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to='profile_pics'),
        ),
    ]
